### ISSUE TITLE
503 Service Unavailable sur la V6 depuis le 03/06

### ISSUE THREAD

**Issue by CFX-SDIS33** [SDIS62/prevarisc-passerelle-platau#27]
Bonjour,

Depuis le 03/06, nous rencontrons une erreur `503 Service Unavailable` lors de tous nos appels à Plat'AU (en **V6**).

En modifiant la valeur de la constante `PLATAU_URL` avec la valeur 'https://api.aife.economie.gouv.fr/mtes/platau/v7/', dans le fichier `src/Service/PlatauAbstract.php`, le `healthcheck` fonctionne correctement, mais pas les autres commandes qui renvoient une erreur `400 Bad Request` ...

Avez-vous rencontré la même problématique ?
Cela signifie-t'il que la V6 de Plat'AU n'est plus disponible et qu'il faut absolument passer sur la V7 (auquel cas il y a visiblement une adaptation du connecteur à réaliser pour le rendre fonctionnel) ?

Merci d'avance pour vos retours.

**Comment by SDIS91** [comment]
Bonjour

Nous avons rencontré le problème. Mais à notre connaissance il n'y a eu aucune annonces sur cette version 7.

**Comment by kdubuc** [comment]
effectivement, même chose côté 62.
Il faut mettre à jour la version de l'API utilisée par la passerelle (voir https://github.com/SDIS62/prevarisc-passerelle-platau/issues/24).

je dois m'assurer que le passage à la v7 ne soit pas bloquant

**Comment by CFX-SDIS33** [comment]
> Bonjour
> 
> Nous avons rencontré le problème. Mais à notre connaissance il n'y a eu aucune annonces sur cette version 7.

Aucune communication non plus de la part du MTES ou de PISTE sur l'arrêt de la V6, le passage en V7...
Ce mode de fonctionnement laisse à désirer si on doit se retrouver devant le fait accompli à chaque changement de version !

**Comment by kdubuc** [comment]
Après contact avec le support Plat'AU, la v6 est retirée définitivement en faveur de la v7 (qui sera retirée à son tour en septembre de cette année, dans 3 mois)

Après revue des changements, voici ce qui peut avoir un impact sur la passerelle :
- Sur la recherche des consultations, attribut nomEtatConsultation : Le critère est maintenant un tableau de valeur fonctionnant en mode IN

Une mise à jour est prévue le 13/06 pour rendre la passerelle à nouveau fonctionelle.

**Comment by CFX-SDIS33** [comment]
Bonjour,

Nous avons récupéré la mise à jour de la passerelle effectuée hier soir (commit `3501f79`).

Pour info, nous rencontrons l'erreur suivante lorsque l'on lance la commande d'import des consultations :
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\Service\PlatauConsultation::parseConsultation() must be of the type array, int given, called in /opt/prevarisc-passerelle-platau/src/Service/PlatauConsultation.php on line 28>
Stack trace:
#0 /opt/prevarisc-passerelle-platau/src/Service/PlatauConsultation.php(28): App\Service\PlatauConsultation->parseConsultation()
#1 [internal function]: App\Service\PlatauConsultation->App\Service\{closure}()
#2 /opt/prevarisc-passerelle-platau/src/Service/PlatauConsultation.php(28): array_map()
#3 /opt/prevarisc-passerelle-platau/src/Command/ImportConsultations.php(46): App\Service\PlatauConsultation->rechercheConsultations()
#4 /opt/prevarisc-passerelle-platau/vendor/symfony/console/Command/Command.php(256): App\Command\ImportConsultations->execute()
#5 /opt/prevarisc-passerelle-platau/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#6 /opt/prevarisc in /opt/prevarisc-passerelle-platau/src/Service/PlatauConsultation.php on line 72
```

**Comment by SDIS52Infotrans** [comment]
Bonjour, même erreur pour nous également suite à la mise à jour de la passerelle.

**Comment by kdubuc** [comment]
Oui, cela est du à la mise en place de la pagination dans Plat'AU qui rend l'ensemble des recherches de la passerelles inopérantes. Je travaille en ce moment même au fix

**Comment by CFX-SDIS33** [comment]
Merci d'avance !

**Comment by kdubuc** [comment]
le commit fix la pagination https://github.com/SDIS62/prevarisc-passerelle-platau/commit/0072da44dc77feeb7faa9181e806f9883591fb3b !

**Comment by SDIS91** [comment]
Bonjour

Merci pour la mise à jour. L'import s'est bien passé, l'import-pieces a retrouvé des dossier mais la réponse contenait la notice suivante:
`PHP Notice:  Undefined index: extension in /var/www/html/prevarisc-passerelle-platau/src/Service/PlatauPiece.php on line 45`
répétée deux fois.
Est-ce que cela pourrait venir de fichiers avec des extensions inconnues (ou sans extension)?

**Comment by kdubuc** [comment]
Actuellement, la passerelle détecte les extensions des pièces via l'entête HTTP Content-Disposition (voir ici https://github.com/SDIS62/prevarisc-passerelle-platau/blob/master/src/Service/PlatauPiece.php#L33)
Je n'ai rien vu dans les documents de la version 7.x une modification du comportement de cette entête pouvant bloquer la détection.
Avez vous la possibilité d'effectuer une requête HTTP via Postman (ou autre client) ?

**Comment by CFX-SDIS33** [comment]
> Bonjour, Confronté au même problème que mes collègues j'ai réalise la mise à jour de la passerelle avec `git pull` puis la mise à jour des dépendances avec `composer install`. Faut-il valider les CGU pour la version 7 au niveau de PISTE ? Suite à cela j'ai l'erreur suivante : `Cient error: 'POST https://api.aife.economie.gouv.fr/mtes/platau/v7/consultations/recherche?numeroPage=0' resulted in a '403 Forbidden' response: {"criteresSurConsultations":{"nomEtatConsultation":[1]}}`
> 
> Pouvez-vous m'aider sur ce problème ? Merci par avance.

Oui, il faut valider les CGU pour la version 7 au niveau de PISTE.
C'est peut-être la cause de votre problème.

**Comment by aechinard** [comment]
Effectivement, c'était bien bien les CGU de la version 7.
Merci beaucoup

**Comment by kdubuc** [comment]
Un GET sur les URL des pièces pour récupérer les entêtes.
Si vous n'avez pas eu de problèmes sur les nouveaux imports cela veut dire que les pièces d'hier n'avaient pas d'extension dans Plat'AU (et donc une mauvaise saisie par le SI).

Je clos le ticket de migration à la v7 ;)

**Comment by nikown** [comment]
Bonjour,
Même problème que plus haut, j'ai fait un git-pull pour avoir la MAJ de la passerelle et composer update / install pour les dépendances.
Sur piste la V7 est bien sélectionné et les CGU accepté.
![image](https://user-images.githubusercontent.com/7092010/175243098-38437d86-848a-4441-bdcd-aadcf2bc2e33.png)

J'ai toujours moi aussi une erreur 403 lors du healthcheck.
Nicolas Decor - SDIS11

**Comment by SDIS52Infotrans** [comment]
Bonjour, le nom de l'API est grisé chez vous, je crois qu'il y a un petit temps après validation des CGU avant que cela ne soit actif.
![image](https://user-images.githubusercontent.com/23100541/175296017-7849d4d9-fac4-49f9-904d-7764c33cf909.png)

**Comment by nikown** [comment]
> Bonjour, le nom de l'API est grisé chez vous, je crois qu'il y a un petit temps après validation des CGU avant que cela ne soit actif. ![image](https://user-images.githubusercontent.com/23100541/175296017-7849d4d9-fac4-49f9-904d-7764c33cf909.png)

C'est bien ça, merci !

![image](https://user-images.githubusercontent.com/7092010/175331815-10118ae8-f842-4b82-871e-4392bfb4d2ae.png)

Où trouve t'on les consultations importées dans Prevarisc ?

Cordialement,
Nicolas Decor - SDIS11
